# common settings
cluster:
  name:elasticsearchnode:
  name: "elasticsearch"
  master: true
  data:truehttp:
  port: 9222
  jsonp:
    enable: false
  cors:
    enabled: true
    allow-origin: "*"
    allow-methods:[OPTIONS, HEAD, GET]index:
  number_of_shards: 5
  number_of_replicas:1index:
  search:
    slowlog:
      threshold:
        query:
          debug: 0s
        fetch:
          debug: 0s
        index:
          debug: 0s